name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin, ccl-bin]
        os: [ubuntu-16.04]

    steps:
      - uses: actions/checkout@v1
      - name: Install curl
        run: |
          sudo apt-get install -y curl
          sudo apt-get install -y libcurl3
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /usr
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Rove
        run: ros install rove
      - name: Install qlot
        run: ros install qlot
      - name: Install dependencies
        run: |
          PATH="~/.roswell/bin:$PATH"
          qlot install
      - name: Run tests      
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove herodotus.asd
